from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill
from typing import List
from io import BytesIO
from datetime import datetime
from ..models import Shift, User


class ExcelExporter:
    """Professional Excel exporter for shifts"""

    @staticmethod
    def export_shifts(shifts: List[Shift], include_agent_info: bool = True) -> BytesIO:
        """
        Export shifts to Excel with professional formatting

        Args:
            shifts: List of Shift objects to export
            include_agent_info: Whether to include agent information

        Returns:
            BytesIO: Excel file in memory
        """
        wb = Workbook()
        ws = wb.active
        ws.title = "Shifts"

        # Define header style
        header_font = Font(bold=True, color="FFFFFF")
        header_fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
        header_alignment = Alignment(horizontal="center", vertical="center")

        # Define headers
        if include_agent_info:
            headers = ["ID", "Agent Name", "Agent Email", "Start Time", "End Time", "Duration (hours)", "Title", "Location", "Description"]
            ws.column_dimensions['A'].width = 8
            ws.column_dimensions['B'].width = 20
            ws.column_dimensions['C'].width = 30
            ws.column_dimensions['D'].width = 20
            ws.column_dimensions['E'].width = 20
            ws.column_dimensions['F'].width = 15
            ws.column_dimensions['G'].width = 20
            ws.column_dimensions['H'].width = 20
            ws.column_dimensions['I'].width = 40
        else:
            headers = ["ID", "Agent ID", "Start Time", "End Time", "Duration (hours)", "Title", "Location", "Description"]
            ws.column_dimensions['A'].width = 8
            ws.column_dimensions['B'].width = 12
            ws.column_dimensions['C'].width = 20
            ws.column_dimensions['D'].width = 20
            ws.column_dimensions['E'].width = 15
            ws.column_dimensions['F'].width = 20
            ws.column_dimensions['G'].width = 20
            ws.column_dimensions['H'].width = 40

        # Write headers
        for col_num, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col_num, value=header)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = header_alignment

        # Write data
        for row_num, shift in enumerate(shifts, 2):
            duration = (shift.end_time - shift.start_time).total_seconds() / 3600

            if include_agent_info:
                data = [
                    shift.id,
                    shift.agent.name if shift.agent else "N/A",
                    shift.agent.email if shift.agent else "N/A",
                    shift.start_time.strftime("%Y-%m-%d %H:%M"),
                    shift.end_time.strftime("%Y-%m-%d %H:%M"),
                    round(duration, 2),
                    shift.title,
                    shift.location or "",
                    shift.description or ""
                ]
            else:
                data = [
                    shift.id,
                    shift.agent_id,
                    shift.start_time.strftime("%Y-%m-%d %H:%M"),
                    shift.end_time.strftime("%Y-%m-%d %H:%M"),
                    round(duration, 2),
                    shift.title,
                    shift.location or "",
                    shift.description or ""
                ]

            for col_num, value in enumerate(data, 1):
                cell = ws.cell(row=row_num, column=col_num, value=value)
                cell.alignment = Alignment(vertical="center")

        # Add metadata sheet
        meta_ws = wb.create_sheet("Metadata")
        meta_ws['A1'] = "Export Date"
        meta_ws['B1'] = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        meta_ws['A2'] = "Total Shifts"
        meta_ws['B2'] = len(shifts)
        meta_ws['A3'] = "Generated By"
        meta_ws['B3'] = "AgentEscala System"

        meta_ws['A1'].font = Font(bold=True)
        meta_ws['A2'].font = Font(bold=True)
        meta_ws['A3'].font = Font(bold=True)
        meta_ws.column_dimensions['A'].width = 20
        meta_ws.column_dimensions['B'].width = 30

        # Save to BytesIO
        output = BytesIO()
        wb.save(output)
        output.seek(0)
        return output

    @staticmethod
    def export_swap_requests(swap_requests: List) -> BytesIO:
        """
        Export swap requests to Excel

        Args:
            swap_requests: List of SwapRequest objects to export

        Returns:
            BytesIO: Excel file in memory
        """
        wb = Workbook()
        ws = wb.active
        ws.title = "Swap Requests"

        # Define header style
        header_font = Font(bold=True, color="FFFFFF")
        header_fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
        header_alignment = Alignment(horizontal="center", vertical="center")

        # Define headers
        headers = [
            "ID", "Status", "Requester", "Target Agent",
            "Origin Shift", "Target Shift", "Reason",
            "Admin Notes", "Created At", "Updated At"
        ]

        # Set column widths
        ws.column_dimensions['A'].width = 8
        ws.column_dimensions['B'].width = 12
        ws.column_dimensions['C'].width = 25
        ws.column_dimensions['D'].width = 25
        ws.column_dimensions['E'].width = 20
        ws.column_dimensions['F'].width = 20
        ws.column_dimensions['G'].width = 40
        ws.column_dimensions['H'].width = 40
        ws.column_dimensions['I'].width = 20
        ws.column_dimensions['J'].width = 20

        # Write headers
        for col_num, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col_num, value=header)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = header_alignment

        # Write data
        for row_num, swap in enumerate(swap_requests, 2):
            data = [
                swap.id,
                swap.status.value,
                swap.requester.name if swap.requester else "N/A",
                swap.target_agent.name if swap.target_agent else "N/A",
                f"Shift #{swap.origin_shift_id}",
                f"Shift #{swap.target_shift_id}",
                swap.reason or "",
                swap.admin_notes or "",
                swap.created_at.strftime("%Y-%m-%d %H:%M"),
                swap.updated_at.strftime("%Y-%m-%d %H:%M")
            ]

            for col_num, value in enumerate(data, 1):
                cell = ws.cell(row=row_num, column=col_num, value=value)
                cell.alignment = Alignment(vertical="center")

        # Add metadata sheet
        meta_ws = wb.create_sheet("Metadata")
        meta_ws['A1'] = "Export Date"
        meta_ws['B1'] = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        meta_ws['A2'] = "Total Swap Requests"
        meta_ws['B2'] = len(swap_requests)
        meta_ws['A3'] = "Generated By"
        meta_ws['B3'] = "AgentEscala System"

        meta_ws['A1'].font = Font(bold=True)
        meta_ws['A2'].font = Font(bold=True)
        meta_ws['A3'].font = Font(bold=True)

        # Save to BytesIO
        output = BytesIO()
        wb.save(output)
        output.seek(0)
        return output
