"""add revoked_refresh_tokens table

Revision ID: 187f6c14d777
Revises: b3dee2c3a703
Create Date: 2026-04-14 22:53:19.463277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identificadores de revisão, usados pelo Alembic.
revision: str = '187f6c14d777'
down_revision: Union[str, None] = 'b3dee2c3a703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_revoked_refresh_token_hash')
    )
    op.create_index(op.f('ix_revoked_refresh_tokens_id'), 'revoked_refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_revoked_refresh_tokens_token_hash'), 'revoked_refresh_tokens', ['token_hash'], unique=True)
    # OCR table already é criada como String/JSON em SQLite na migration anterior.
    # Esses ALTER COLUMN são necessários apenas no PostgreSQL.
    if op.get_bind().dialect.name == "postgresql":
        op.alter_column('ocr_imports', 'id',
                   existing_type=sa.UUID(),
                   type_=sa.String(length=36),
                   existing_nullable=False)
        op.alter_column('ocr_imports', 'raw_payload',
                   existing_type=postgresql.JSONB(astext_type=sa.Text()),
                   type_=sa.JSON(),
                   existing_nullable=True)
        op.alter_column('ocr_imports', 'parsed_rows',
                   existing_type=postgresql.JSONB(astext_type=sa.Text()),
                   type_=sa.JSON(),
                   existing_nullable=True)
        op.alter_column('ocr_imports', 'errors',
                   existing_type=postgresql.JSONB(astext_type=sa.Text()),
                   type_=sa.JSON(),
                   existing_nullable=True)
        op.alter_column('ocr_imports', 'action_log',
                   existing_type=postgresql.JSONB(astext_type=sa.Text()),
                   type_=sa.JSON(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.alter_column('ocr_imports', 'action_log',
                   existing_type=sa.JSON(),
                   type_=postgresql.JSONB(astext_type=sa.Text()),
                   existing_nullable=True)
        op.alter_column('ocr_imports', 'errors',
                   existing_type=sa.JSON(),
                   type_=postgresql.JSONB(astext_type=sa.Text()),
                   existing_nullable=True)
        op.alter_column('ocr_imports', 'parsed_rows',
                   existing_type=sa.JSON(),
                   type_=postgresql.JSONB(astext_type=sa.Text()),
                   existing_nullable=True)
        op.alter_column('ocr_imports', 'raw_payload',
                   existing_type=sa.JSON(),
                   type_=postgresql.JSONB(astext_type=sa.Text()),
                   existing_nullable=True)
        op.alter_column('ocr_imports', 'id',
                   existing_type=sa.String(length=36),
                   type_=sa.UUID(),
                   existing_nullable=False)
    op.drop_index(op.f('ix_revoked_refresh_tokens_token_hash'), table_name='revoked_refresh_tokens')
    op.drop_index(op.f('ix_revoked_refresh_tokens_id'), table_name='revoked_refresh_tokens')
    op.drop_table('revoked_refresh_tokens')
    # ### end Alembic commands ###
